global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "market-nyse"
    static_configs:
      - targets: ["localhost:19885"]
    metrics_path: "/metrics"

  - job_name: "market-nasdaq"
    static_configs:
      - targets: ["localhost:19870"]
    metrics_path: "/metrics"
