global:
  scrape_interval: 15s # How often to ask for metrics
  evaluation_interval: 15s

scrape_configs:
  - job_name: "market-nyse"
    static_configs:
      - targets: ["localhost:9885"] # Your web server address
    metrics_path: "/metrics" # Endpoint to scrape

  - job_name: "market-nasdaq"
    static_configs:
      - targets: ["localhost:9870"] # Your web server address
    metrics_path: "/metrics" # Endpoint to scrape
